# Generated by Django 2.0.3 on 2020-05-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
