# Generated by Django 2.0.3 on 2020-05-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_auto_20200519_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='sets',
            field=models.ManyToManyField(blank=True, null=True, related_name='set', to='web_app.Set'),
        ),
    ]
