# Generated by Django 2.0.3 on 2020-05-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_auto_20200519_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='set_colour',
            field=models.ManyToManyField(blank=True, default='enter_colour', null=True, related_name='set_colour', to='web_app.Colour'),
        ),
    ]
