# Generated by Django 2.0.3 on 2020-05-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_set_set_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='item_photo',
            field=models.ManyToManyField(blank=True, default='add photo', null=True, related_name='item_photo', to='web_app.Photo'),
        ),
        migrations.AddField(
            model_name='set',
            name='set_photo',
            field=models.ManyToManyField(blank=True, default='add photo', null=True, related_name='set_photo', to='web_app.Photo'),
        ),
    ]
